// Addresses that live outside this site: the public repository, the two
// release tags it publishes, and the site's own canonical origin.
//
// One module for all of them because the same handful of URLs is spelled on
// the home page, in the page header, in the public README and in the Rust
// CLI's own defaults. A release URL that is right in one place and stale in
// another sends the reader to a 404 and nothing fails anywhere, so the copies
// are collapsed here and `rust/nanourl/tests/goldens/cli.json` (generated by
// `scripts/cli-goldens.ts`) carries them across the language boundary.

/** The public repository: the site's source, the weights and the CLI. */
export const REPO_URL = 'https://github.com/howforge-dev/nanourl';

/** Where the site is served. The CLI's `--link` default, so a link minted on
 *  the command line and a link minted in the browser are the same string. */
export const SITE_URL = 'https://qv.lc/';

/** The release the model weights ship under — too large for git, so they are
 *  a tagged asset the browser and CI both fetch by the same URL, and the one
 *  the `nanourl` binary is built around. */
export const MODEL_RELEASE_URL = `${REPO_URL}/releases/tag/model-v0`;

/** The weights themselves: what the browser streams, what CI packs, and what
 *  `nanourl model info` names as the release its embedded copy came from. */
export const MODEL_ASSET_URL = `${REPO_URL}/releases/download/model-v0/nanourl-target-base.nurl`;

/** Every release, including the `cli-v*` tags that carry the prebuilt
 *  `nanourl` binaries for Linux, macOS and Windows. */
export const RELEASES_URL = `${REPO_URL}/releases`;
