// GENERATED by web/scripts/numbers.ts — do not hand-edit. Regenerate: `pnpm exec tsx scripts/numbers.ts`
// Source manifest:     scripts/fixtures/manifest.json
// Source eval:         scripts/fixtures/eval-final.txt
// Source hn trace:     scripts/fixtures/hn-trace.json
// Source zip sizes:    scripts/fixtures/zip-sizes.json (deflate/gzip re-measured with node zlib 1.3.1-e00f703)
// Source artifact:     ../models/target-base/ptq.nurl sha256 5e37aad1f34c420f2a3f5ea5a273ec3bd95a99b48f0c3eaa29187b1d22039fd2
// Generated:           2026-09-08T06:25:10.290Z
//
// Every numeric fact the learn page shows comes from here.
// `artifactSha256` is the gate: tests/assets-sync.test.ts fails if the model
// `task web:assets` packed into web/public isn't the one described here.

export interface HnTraceToken {
  piece: string;
  bits: number;
  clo?: number;
  chi?: number;
}

export interface Numbers {
  params: number;
  layers: number;
  dModel: number;
  heads: number;
  headDim: number;
  dMlp: number;
  vocab: number;
  block: number;
  trainTokens: number;
  datasetUrls: number;
  datasetTokens: number;
  trainPasses: number;
  meanTokensPerUrl: number;
  bitsPerChar: number;
  bitsPerCharKernel: number;
  bitsPerCharKernelReal: number | null;
  evalUrls: number;
  evalUrlsSkipped: number;
  artifactBytes: number;
  artifactMiB: number;
  /** sha256 of the .nurl artifact these numbers describe — the anchor
   *  tests/assets-sync.test.ts checks web/src/lib/assets.json against. */
  artifactSha256: string;
  f32MiB: number;
  ratio: number;
  evalShard: number;
  evalSource: string;
  tokenizerSha256: string;
  zip: { raw: number; deflate: number; gzip: number; bzip2: number; xz: number };
  hn: {
    url: string;
    canonical: string;
    coded: string;
    url_chars: number;
    coded_chars: number;
    coded_bits: number;
    model_bits: number;
    bits_per_char: number;
    ratio: number;
    tokens: HnTraceToken[];
  };
  static: {
    rfcDelimiters: number;
    groupSize: number;
    probGridBits: number;
    streamVersion: number;
    chainCarry: number;
    maxTokenLength: number;
    chunkMiB: number;
    quantBits: number;
    quantLevels: number;
    quantHalfRange: number;
    gpuCount: number;
    alphabets: readonly string[];
    alphabetSizes: Readonly<Record<string, number>>;
    int4RoundingNoTailPct: number;
    int4TailGapPct: number;
  };
}

export const numbers: Numbers = {
  "params": 246087680,
  "layers": 12,
  "dModel": 1280,
  "heads": 20,
  "headDim": 64,
  "dMlp": 3392,
  "vocab": 8192,
  "block": 512,
  "trainTokens": 19922944000,
  "datasetUrls": 1463118092,
  "datasetTokens": 51927702104,
  "trainPasses": 0.38,
  "meanTokensPerUrl": 35.4911,
  "bitsPerChar": 1.2629,
  "bitsPerCharKernel": 1.26372,
  "bitsPerCharKernelReal": 1.2952,
  "evalUrls": 100000,
  "evalUrlsSkipped": 74,
  "artifactBytes": 130862112,
  "artifactMiB": 124.7998,
  "artifactSha256": "5e37aad1f34c420f2a3f5ea5a273ec3bd95a99b48f0c3eaa29187b1d22039fd2",
  "f32MiB": 938.75,
  "ratio": 7.522,
  "evalShard": 512,
  "evalSource": "part-00512.parquet, even stride",
  "tokenizerSha256": "6e4f2b4fa9de153b27adaee016dc3f2586ac886423f0153858b89e13f31be374",
  "zip": {
    "raw": 45,
    "deflate": 43,
    "gzip": 61,
    "bzip2": 83,
    "xz": 104
  },
  "hn": {
    "url": "https://news.ycombinator.com/item?id=38000000",
    "canonical": "https://com.ycombinator.news/item?id=38000000",
    "coded": "IDrqYQdZ",
    "url_chars": 45,
    "coded_chars": 8,
    "coded_bits": 43,
    "model_bits": 41.79,
    "bits_per_char": 0.9556,
    "ratio": 0.1778,
    "tokens": [
      {
        "piece": "https://",
        "bits": 0.73,
        "clo": 0.000016,
        "chi": 0.60434
      },
      {
        "piece": "com",
        "bits": 1.14,
        "clo": 0.012523,
        "chi": 0.464821
      },
      {
        "piece": ".",
        "bits": 0,
        "clo": 0.000001,
        "chi": 0.999513
      },
      {
        "piece": "y",
        "bits": 8.26,
        "clo": 0.077204,
        "chi": 0.080476
      },
      {
        "piece": "com",
        "bits": 6.41,
        "clo": 0.096971,
        "chi": 0.108767
      },
      {
        "piece": "bin",
        "bits": 0,
        "clo": 0.000181,
        "chi": 0.999472
      },
      {
        "piece": "ator",
        "bits": 0,
        "clo": 0.000541,
        "chi": 0.999374
      },
      {
        "piece": ".",
        "bits": 0,
        "clo": 0.000038,
        "chi": 0.998561
      },
      {
        "piece": "news",
        "bits": 0.03,
        "clo": 0.016988,
        "chi": 0.993715
      },
      {
        "piece": "/",
        "bits": 0,
        "clo": 0.000024,
        "chi": 0.999509
      },
      {
        "piece": "item",
        "bits": 0.26,
        "clo": 0.033703,
        "chi": 0.867258
      },
      {
        "piece": "?",
        "bits": 0,
        "clo": 0.000057,
        "chi": 0.999512
      },
      {
        "piece": "id",
        "bits": 0,
        "clo": 0.000018,
        "chi": 0.99953
      },
      {
        "piece": "=",
        "bits": 0,
        "clo": 0.0000018,
        "chi": 0.999514
      },
      {
        "piece": "38",
        "bits": 6.63,
        "clo": 0.462644,
        "chi": 0.472729
      },
      {
        "piece": "000000",
        "bits": 18.19,
        "clo": 0.766254,
        "chi": 0.766258
      },
      {
        "piece": "<eos>",
        "bits": 0.13,
        "clo": 0,
        "chi": 0.912085
      }
    ]
  },
  "static": {
    "rfcDelimiters": 29,
    "groupSize": 64,
    "probGridBits": 24,
    "streamVersion": 0,
    "chainCarry": 256,
    "maxTokenLength": 24,
    "chunkMiB": 8,
    "quantBits": 4,
    "quantLevels": 15,
    "quantHalfRange": 7,
    "gpuCount": 8,
    "alphabets": [
      "base64url",
      "base79",
      "emoji-1k",
      "qr-alpha"
    ],
    "alphabetSizes": {
      "base64url": 64,
      "base79": 79,
      "emoji-1k": 1024,
      "qr-alpha": 43
    },
    "int4RoundingNoTailPct": 8.3,
    "int4TailGapPct": 1.3
  }
} as const;
