// Pure logic for scripts/numbers.ts, split out so vitest can exercise the
// failure mode (a manifest missing a field) without touching the filesystem
// or shelling out to python3. See scripts/numbers.ts for the CLI that reads
// the real manifest.json / eval-final.txt and calls buildNumbers().

import { MIB } from '../src/lib/format';

export interface HnTraceToken {
  piece: string;
  bits: number;
  // this token's own slice of that step's fresh [0,1) probability line —
  // clo/chi, i.e. C(s)/TOTAL and (C(s)+P(s))/TOTAL from rust/urlcodec's
  // codec_encode. Optional: only the coder figures need it.
  clo?: number;
  chi?: number;
}

export interface HnTrace {
  url: string;
  canonical: string;
  coded: string;
  url_chars: number;
  coded_chars: number;
  coded_bits: number;
  model_bits: number;
  bits_per_char: number;
  ratio: number;
  tokens: HnTraceToken[];
}

export interface ZipSizes {
  raw: number;
  deflate: number;
  gzip: number;
  bzip2: number;
  xz: number;
}

// Facts that are true by construction of the codec/tokenizer, not measured
// per training run — see rust/urlcodec/src/coder.rs (PROB_BITS, GROUP,
// STREAM_VERSION) and docs/tokenization.md (29 delimiters, generated by
// `task docs` from training/canonical.py).
export interface StaticFacts {
  rfcDelimiters: number;
  groupSize: number;
  probGridBits: number;
  streamVersion: number;
  chainCarry: number;
  maxTokenLength: number;
  chunkMiB: number;
  // int4 PTQ+QAT layout (rust/urlcodec's `.nurl` v3):
  // groupSize weights share one f16 scale, each weight one of quantLevels signed
  // steps from -quantHalfRange to +quantHalfRange.
  quantBits: number;
  quantLevels: number;
  quantHalfRange: number;
  // training hardware for this artifact: 8x RTX 5090
  gpuCount: number;
  alphabets: readonly string[];
  // character-set sizes for each alphabet — rust/urlcodec/src/coder.rs's
  // ALPHABET (79), ALPHABET64 (64) and ALPHABET_EMOJI_1K (1024); bits/char
  // is derived from these (log2), not a separate hardcoded figure
  alphabetSizes: Readonly<Record<string, number>>;
  // int4 PTQ (no QAT tail) vs the shipped QAT-tail kernel_sim bits/char, as a
  // percent regression relative to fp32 — production QAT ablation; not yet
  // re-derivable from a committed experiment file.
  int4RoundingNoTailPct: number;
  // What the QAT tail still leaves on the table, as a percent regression
  // against the SAME full-precision checkpoint int4RoundingNoTailPct is
  // measured against. Both must share that baseline or the pair reads as a
  // recovery it is not.
  int4TailGapPct: number;
}

// No timing facts live here. A device's speed is a property of that device,
// so the only honest figure is the one /bench.html measures on the machine
// reading it; a stored table invites the site to quote someone else's laptop
// at a visitor as if it were a promise.

export interface NumbersData {
  params: number;
  layers: number;
  dModel: number;
  heads: number;
  headDim: number;
  dMlp: number;
  vocab: number;
  block: number;
  trainTokens: number;
  /** Distinct URLs *available* to training across the whole corpus — not how
   *  many it saw. Training draws random windows with no epochs, so the URLs it
   *  actually consumed is `trainTokens / meanTokensPerUrl`, a different and
   *  much smaller number. */
  datasetUrls: number;
  /** Tokens in the whole corpus, the denominator `trainPasses` divides. */
  datasetTokens: number;
  /** Corpus fraction training covered: trainTokens / datasetTokens. Below 1
   *  here, which is why nothing on the site may call it a pass count. */
  trainPasses: number;
  meanTokensPerUrl: number;
  bitsPerChar: number;
  bitsPerCharKernel: number;
  bitsPerCharKernelReal: number | null;
  evalUrls: number;
  evalUrlsSkipped: number;
  artifactBytes: number;
  artifactMiB: number;
  /** sha256 of the .nurl file these numbers were generated against. The
   *  manifest records the artifact's *length* (`model.artifact_bytes`) but
   *  nothing about its content, and length is a pure function of the config:
   *  two runs of the same config produce byte-identical-sized artifacts with
   *  completely different weights — a learn page generated from one run's
   *  manifest could ship beside another run's export with every other gate
   *  green. The digest is the one field that can tell those
   *  apart, so it travels with the numbers. */
  artifactSha256: string;
  f32MiB: number;
  ratio: number;
  evalShard: number;
  evalSource: string;
  tokenizerSha256: string;
  zip: ZipSizes;
  hn: HnTrace;
  static: StaticFacts;
}

/** Read a required, dotted-path field off an arbitrary JSON object, throwing
 *  loudly (naming the manifest and the path) if it is missing or null — the
 *  whole point of generating numbers.ts from the manifest is that a field
 *  silently going missing must break the build, not ship a stale number. */
export function required(obj: unknown, path: string, sourceLabel: string): unknown {
  const parts = path.split('.');
  let cur: unknown = obj;
  for (const p of parts) {
    if (cur === null || typeof cur !== 'object' || !(p in (cur as Record<string, unknown>))) {
      throw new Error(`${sourceLabel}: missing required field "${path}"`);
    }
    cur = (cur as Record<string, unknown>)[p];
  }
  if (cur === null || cur === undefined) {
    throw new Error(`${sourceLabel}: required field "${path}" is null/undefined`);
  }
  return cur;
}

function num(obj: unknown, path: string, sourceLabel: string): number {
  const v = required(obj, path, sourceLabel);
  if (typeof v !== 'number' || Number.isNaN(v)) {
    throw new Error(`${sourceLabel}: field "${path}" is not a number (got ${JSON.stringify(v)})`);
  }
  return v;
}

function str(obj: unknown, path: string, sourceLabel: string): string {
  const v = required(obj, path, sourceLabel);
  if (typeof v !== 'string' || v.length === 0) {
    throw new Error(`${sourceLabel}: field "${path}" is not a non-empty string (got ${JSON.stringify(v)})`);
  }
  return v;
}

/** Parse eval-final.txt's three lines. Throws if the fp32 or kernel_sim lines
 *  are missing; the real-kernel line (rust/nurlcheck, a smaller sample) is
 *  optional because not every eval run scores it. */
export function parseEvalText(text: string, sourceLabel: string) {
  const fp = /fp32:\s*([\d.]+)\s*bits\/char over (\d+) URLs \((\d+) skipped\)/.exec(text);
  if (!fp) throw new Error(`${sourceLabel}: missing "fp32: ... bits/char over N URLs (M skipped)" line`);
  const ks = /kernel_sim\(int4\):\s*([\d.]+)\s*bits\/char/.exec(text);
  if (!ks) throw new Error(`${sourceLabel}: missing "kernel_sim(int4): ... bits/char" line`);
  const kr = /kernel:\s*([\d.]+)\s*bits\/char \(rust\/nurlcheck\) over (\d+) URLs/.exec(text);
  return {
    bitsPerChar: Number(fp[1]),
    evalUrlsScored: Number(fp[2]),
    evalUrlsSkipped: Number(fp[3]),
    bitsPerCharKernel: Number(ks[1]),
    bitsPerCharKernelReal: kr ? Number(kr[1]) : null,
  };
}

/** The packed `.nurl` artifact, hashed by the caller (scripts/numbers.ts). */
export interface ArtifactFacts {
  sha256: string;
  bytes: number;
}

// The training corpus is shards 0-39 of the tokenized dataset; the manifest
// shipped beside the artifact lists only the ten shards the QAT tail re-read,
// so its data.total_* describe a quarter of what training drew from. The
// shards are hash-partitioned and equal-sized to within 0.1%, so the corpus is
// the tail's ten scaled by the shard ratio — the same derivation
// tools/publish/release-manifest.py applies to the public manifest, so the
// site and the release cannot disagree. CORPUS_* are the independently
// recorded totals the scaling is checked against.
const TAIL_SHARD_COUNT = 10;
const TRAIN_SHARD_COUNT = 40;
const CORPUS_TOKENS = 51.9e9;
const CORPUS_URLS = 1.46e9;
const SCALE_TOLERANCE = 0.01;

/** A tail-manifest total scaled to the whole corpus, refused if it drifts from
 *  the recorded total — a silently mis-scaled corpus is worse than no figure. */
function scaledToCorpus(value: number, expected: number, label: string): number {
  // A manifest that already lists the whole corpus (the published one, with
  // totals for all forty shards) needs no scaling; only the tail's ten do.
  if (Math.abs(value / expected - 1) <= SCALE_TOLERANCE) return value;
  const total = value * (TRAIN_SHARD_COUNT / TAIL_SHARD_COUNT);
  if (Math.abs(total / expected - 1) > SCALE_TOLERANCE) {
    throw new Error(
      `${label}: scaling the manifest's ${value} to ${TRAIN_SHARD_COUNT} shards gives ${total}, ` +
        `more than ${SCALE_TOLERANCE * 100}% from the recorded ${expected}`,
    );
  }
  return total;
}

export function buildNumbers(
  manifest: unknown,
  evalText: string,
  zip: ZipSizes,
  hn: HnTrace,
  staticFacts: StaticFacts,
  artifact: ArtifactFacts,
): NumbersData {
  const m = 'manifest.json';
  const params = num(manifest, 'model.n_params', m);
  const artifactBytes = num(manifest, 'model.artifact_bytes', m);
  const artifactMiB = Math.round(num(manifest, 'model.artifact_mib', m) * 1e4) / 1e4;
  const layers = num(manifest, 'config.model.n_layer', m);
  const dModel = num(manifest, 'config.model.d_model', m);
  const heads = num(manifest, 'config.model.n_head', m);
  const headDim = num(manifest, 'model_config.head_dim', m);
  const dMlp = num(manifest, 'model_config.d_mlp', m);
  const vocab = num(manifest, 'model_config.vocab', m);
  const block = num(manifest, 'model_config.block', m);
  const iters = num(manifest, 'config.train.iters', m);
  const tokensPerIter = num(manifest, 'schedule.tokens_per_iter', m);
  const evalUrls = num(manifest, 'config.train.final_eval_urls', m);
  const totalTokens = num(manifest, 'data.total_tokens', m);
  const totalUrls = num(manifest, 'data.total_urls', m);
  const evalShard = num(manifest, 'data.eval_shard', m);
  // The manifest may prefix the source with the Hub repo it was read from;
  // the site names the shard file and the sampling rule, not a data owner.
  const evalSource = str(manifest, 'data.eval_source', m).replace(/^[\w.-]+\/[\w.-]+\s+/, '');
  const tokenizerSha256 = str(manifest, 'data.tokenizer_sha256', m);

  const trainTokens = iters * tokensPerIter;
  // Ratio, so it is the same whether the manifest lists ten shards or forty.
  const meanTokensPerUrlExact = totalTokens / totalUrls;
  const corpusTokens = scaledToCorpus(totalTokens, CORPUS_TOKENS, 'data.total_tokens');
  const corpusUrls = scaledToCorpus(totalUrls, CORPUS_URLS, 'data.total_urls');
  const trainPasses = Math.round((trainTokens / corpusTokens) * 100) / 100;
  // rounded only for the emitted file: full precision isn't meaningful past
  // a few decimals here, and eslint's no-loss-of-precision flags the raw
  // 16-significant-digit division result as a literal in generated code
  const meanTokensPerUrl = Math.round(meanTokensPerUrlExact * 1e4) / 1e4;
  const f32MiB = (params * 4) / MIB;
  const ratio = Math.round((f32MiB / artifactMiB) * 1e4) / 1e4;

  // The cheapest thing that can be checked between "the manifest describing
  // the run" and "the file on disk": a length disagreement means the --nurl
  // passed is not the artifact this manifest exported.
  if (artifact.bytes !== artifactBytes) {
    throw new Error(
      `the --nurl artifact is ${artifact.bytes} bytes but manifest.json's model.artifact_bytes is ` +
        `${artifactBytes} — the manifest and the artifact are from different runs`,
    );
  }
  if (!/^[0-9a-f]{64}$/.test(artifact.sha256)) {
    throw new Error(`artifact sha256 must be 64 lowercase hex characters, got ${JSON.stringify(artifact.sha256)}`);
  }

  const ev = parseEvalText(evalText, 'eval-final.txt');
  if (ev.evalUrlsScored + ev.evalUrlsSkipped !== evalUrls) {
    throw new Error(
      `eval-final.txt and manifest.json disagree on the eval set size: ` +
        `${ev.evalUrlsScored} + ${ev.evalUrlsSkipped} scored+skipped vs config.train.final_eval_urls=${evalUrls}`,
    );
  }

  return {
    params,
    layers,
    dModel,
    heads,
    headDim,
    dMlp,
    vocab,
    block,
    trainTokens,
    datasetUrls: corpusUrls,
    datasetTokens: corpusTokens,
    trainPasses,
    meanTokensPerUrl,
    bitsPerChar: ev.bitsPerChar,
    bitsPerCharKernel: ev.bitsPerCharKernel,
    bitsPerCharKernelReal: ev.bitsPerCharKernelReal,
    evalUrls,
    evalUrlsSkipped: ev.evalUrlsSkipped,
    artifactBytes,
    artifactMiB,
    artifactSha256: artifact.sha256,
    f32MiB,
    ratio,
    evalShard,
    evalSource,
    tokenizerSha256,
    zip,
    hn,
    static: staticFacts,
  };
}
