import rawManifest from '../assets.json';
import { isModelCache, MODEL_CACHE_PREFIX } from './cacheNames';
import type { AssetEntry, Manifest } from './manifest';
import { RateMeter, downloadParts, partsText } from './progress';
import type { Progress } from './types';

// Re-exported so existing importers (Atlas.svelte, the tests) keep one path
// to the shape; it is declared once in ./manifest.
export type { AssetEntry, Manifest };

// assets.json is generated by web/scripts/pack-assets.ts (gitignored, built by
// `task web:assets`); wasmMt/wasmRelaxed/atlas are null when the
// corresponding build wasn't passed to pack-assets (e.g. a fresh checkout
// before `task codec:wasm` has produced every tier).
const manifest = rawManifest as Manifest;

/**
 * Cache API bucket, versioned by the model this bundle ships.
 *
 * The name MUST carry the model digest. `pruneCache()` deletes everything not
 * in *this* bundle's manifest and runs on every load, so a shared bucket
 * across a deploy means tab A (still on yesterday's bundle) reloads and
 * deletes all 7 new chunks, tab B reloads and deletes the 7 old ones: 125 MiB
 * per swing, ping-ponging until every stale tab closes. Per-model names mean
 * the two bundles do not share a cache at all, and the sweep below reclaims
 * the loser's space rather than orphaning it: `pruneCache` only enumerates
 * *inside* its own bucket, never `caches.keys()`, so without that sweep a
 * bumped name strands 125 MiB in the user's quota forever.
 */
export const MODEL_CACHE_NAME = `${MODEL_CACHE_PREFIX}${manifest.model.sha256.slice(0, 8)}`;
const CACHE = MODEL_CACHE_NAME;

/** Is `key` a *model* cache from a previous deploy of this app, i.e. safe to
 * reclaim? Pure and exported so `tests/loader.test.ts` can pin the exclusions
 * (a sibling's `nanourl-shell-v1` must survive) without a Cache API.
 *
 * `isModelCache` (cacheNames.ts) matches exactly the shape `MODEL_CACHE_NAME`
 * mints (`nanourl-` plus the model digest's first 8 lowercase hex
 * characters) and NOT a bare `nanourl-` prefix. The sweep below runs on every
 * load and deletes what it matches, so matching the prefix would eat any
 * other bucket a sibling of this code owns, concretely `nanourl-shell-*`, the
 * service worker's offline shell. */
export function isStaleModelCache(key: string, current: string = MODEL_CACHE_NAME): boolean {
  return isModelCache(key) && key !== current;
}

export interface WasmPick {
  entry: AssetEntry;
  threads: number;
  kind: 'threads' | 'relaxed' | 'simd';
}

/** Which wasm tier to fetch for a given feature-detection (or bench-forced)
 * result: threads > 0 wins outright (needs the mt build to exist), else
 * relaxed-SIMD if the manifest has that build, else the portable simd128
 * fallback every manifest always has. `threads` is clamped to 0 whenever the
 * mt build isn't selected, so callers can pass it straight to codec_init
 * without re-deriving "did we get the mt wasm"; `kind` names which branch
 * fired, so a caller (`client.ts`'s tier
 * fallback) can tell "asked for threads, got simd because mt was missing"
 * apart from "asked for threads, got threads, then threads failed at
 * runtime" without re-deriving that either.
 *
 * `m` defaults to the real packed manifest but takes an explicit one so
 * `pickWasm` can be unit tested against synthetic fixtures covering all
 * three configurations (mt+relaxed+simd, relaxed+simd only, simd only)
 * instead of whatever `task web:assets` happened to pack on this checkout;
 * see `tests/loader.test.ts`. */
export function pickWasm(tier: { relaxed: boolean; threads: number }, m: Manifest = manifest): WasmPick {
  if (tier.threads > 0 && m.wasmMt) return { entry: m.wasmMt, threads: tier.threads, kind: 'threads' };
  if (tier.relaxed && m.wasmRelaxed) return { entry: m.wasmRelaxed, threads: 0, kind: 'relaxed' };
  return { entry: m.wasm, threads: 0, kind: 'simd' };
}

export const assemble = (parts: Uint8Array[], total: number): Uint8Array => {
  const out = new Uint8Array(total);
  let o = 0;
  for (const p of parts) {
    out.set(p, o);
    o += p.length;
  }
  return out;
};

export const weightsFor = (chunkBytes: number[], ...others: number[]): number[] => {
  const all = [...chunkBytes, ...others];
  const t = all.reduce((a, b) => a + b, 0);
  return all.map((b) => b / t);
};

const INSECURE_CONTEXT =
  'this page is not a secure context, so crypto.subtle is unavailable and downloaded ' +
  'model chunks cannot be verified; serve the app over https (or from localhost)';

/** Throws a *named* error when the page is not a secure context, instead of
 * letting `crypto.subtle.digest` fail with a bare `TypeError: Cannot read
 * properties of undefined`. Called once before any download starts, so a
 * plain-HTTP deploy fails in a second with an explanation rather than after
 * ~125 MiB. `SharedArrayBuffer` and `caches` are unavailable there too; see
 * web/README.md's "HTTPS is required". */
export function assertSecureContext(): void {
  if (typeof crypto === 'undefined' || !crypto.subtle) throw new Error(INSECURE_CONTEXT);
}

async function sha256Hex(b: Uint8Array): Promise<string> {
  assertSecureContext();
  // Every Uint8Array here is backed by a plain (never Shared) ArrayBuffer,
  // assembled locally or read from fetch/Cache, but TS's generic typed-array
  // param widens to ArrayBufferLike, which BufferSource/BodyInit reject.
  const d = await crypto.subtle.digest('SHA-256', b as Uint8Array<ArrayBuffer>);
  return Array.from(new Uint8Array(d))
    .map((x) => x.toString(16).padStart(2, '0'))
    .join('');
}

async function cached(name: string): Promise<Uint8Array | null> {
  try {
    const c = await caches.open(CACHE);
    const hit = await c.match('/' + name);
    return hit ? new Uint8Array(await hit.arrayBuffer()) : null;
  } catch {
    return null;
  }
}

async function store(name: string, bytes: Uint8Array): Promise<void> {
  try {
    const c = await caches.open(CACHE);
    await c.put('/' + name, new Response(bytes as Uint8Array<ArrayBuffer>));
  } catch {
    /* best-effort */
  }
}

async function evict(name: string): Promise<void> {
  try {
    const c = await caches.open(CACHE);
    await c.delete('/' + name);
  } catch {
    /* no Cache API; nothing was cached to begin with */
  }
}

/** Delete every *model* cache bucket that isn't this bundle's, the other half
 * of the per-model cache naming. Without it, bumping CACHE orphans the
 * previous model's ~125 MiB in the user's quota with nothing that can ever
 * reclaim it.
 * See `isStaleModelCache` for why this is not a prefix match. */
async function pruneOldCaches(): Promise<void> {
  try {
    for (const key of await caches.keys()) {
      if (isStaleModelCache(key)) await caches.delete(key);
    }
  } catch {
    /* no Cache API */
  }
}

/** Delete any cached asset whose name is not in the current manifest. */
export async function pruneCache(): Promise<void> {
  await pruneOldCaches();
  try {
    const c = await caches.open(CACHE);
    const keep = new Set(
      [
        ...manifest.model.chunks.map((ch) => ch.name),
        manifest.tokenizer.name,
        manifest.wasm.name,
        manifest.wasmMt?.name,
        manifest.wasmRelaxed?.name,
        manifest.atlas?.name,
      ].filter((n): n is string => Boolean(n)),
    );
    for (const req of await c.keys()) {
      const name = new URL(req.url).pathname.split('/').pop();
      if (!name || !keep.has(name)) await c.delete(req);
    }
  } catch {
    /* no Cache API */
  }
}

/** `fromCache` says the bytes came out of the Cache API rather than the
 * network. The status line reports a restore and a cold download very
 * differently (no speed or ETA is meaningful for a restore), and the caller
 * cannot tell them apart from the byte counts alone. */
export type OnBytes = (got: number, fromCache?: boolean) => void;

/** True for the DOMException a fetch aborted via AbortController throws. An
 * abort is a deliberate cancellation, never something to retry or report. */
const isAbort = (e: unknown) => e instanceof Error && e.name === 'AbortError';

/**
 * Download one asset, verifying it, with 3 attempts and backoff.
 *
 * The digest check is **inside** the retry loop, not in `fetchAsset` around
 * it. A CDN edge closing a chunked response early is a *clean* close: `done`
 * fires, `assemble` returns a short buffer, and no transport error is
 * raised, so a check outside the loop fails the whole load with "checksum
 * mismatch" in exactly the case a retry fixes.
 */
async function download(a: AssetEntry, onBytes: OnBytes, signal?: AbortSignal): Promise<Uint8Array> {
  for (let attempt = 0; ; attempt++) {
    try {
      const r = await fetch('/' + a.name, signal ? { signal } : undefined);
      if (!r.ok) throw new Error(`${a.name}: HTTP ${r.status}`);
      const reader = r.body!.getReader();
      const parts: Uint8Array[] = [];
      let got = 0;
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        parts.push(value);
        got += value.length;
        // Outside the try below on purpose: a throwing progress callback is a
        // caller bug, not a network failure, and must not spend two backoff
        // retries pretending otherwise.
        queueProgress(onBytes, Math.min(got, a.bytes));
      }
      const bytes = assemble(parts, got);
      if (bytes.length !== a.bytes) throw new Error(`${a.name}: short read (${bytes.length} of ${a.bytes} bytes)`);
      if ((await sha256Hex(bytes)) !== a.sha256) throw new Error(`${a.name}: checksum mismatch`);
      return bytes;
    } catch (e) {
      if (isAbort(e) || attempt >= 2) throw e;
      await new Promise((res) => setTimeout(res, 1000 << attempt));
    }
  }
}

/** Run a progress callback without letting it be mistaken for a network
 * error: `download`'s retry loop wraps the transport, so an `onBytes` that
 * throws would otherwise land in that catch and trigger two backoff retries. */
function queueProgress(onBytes: OnBytes, got: number, fromCache = false): void {
  try {
    onBytes(got, fromCache);
  } catch {
    /* a broken progress callback must never fail a download */
  }
}

/**
 * Fetch one named asset: length-checked cache hit -> network (3 attempts,
 * each length- and digest-verified) -> cache.
 *
 * The digest is verified **once**, on download, before the bytes are ever
 * written to the cache, so everything in the cache was correct when it went
 * in. A cache hit is checked against the manifest's byte length, and a
 * mismatch evicts the entry and falls through to the network (where the full
 * hash check applies). Re-hashing 125 MiB on every single load to defend
 * against a Cache API that silently corrupts at rest is not a trade worth
 * making; the length check is what catches the realistic failure: a
 * truncated or wrongly-sized entry.
 *
 * The read path must verify, not only the write path. A bad cache entry goes
 * straight into wasm memory and `codec_init` runs over it, and it is
 * **permanent** without delete-then-refetch here: `pruneCache` filters by name
 * only, so every later load reads the same bytes and only "clear site data"
 * recovers.
 */
export async function fetchAsset(a: AssetEntry, onBytes: OnBytes, signal?: AbortSignal): Promise<Uint8Array> {
  const hit = await cached(a.name);
  if (hit) {
    if (hit.length === a.bytes) {
      queueProgress(onBytes, a.bytes, true);
      return hit;
    }
    await evict(a.name); // wrong size at rest: never replay it, refetch once
  }
  const bytes = await download(a, onBytes, signal);
  await store(a.name, bytes);
  return bytes;
}

/** Total model bytes across all chunks, known statically from the manifest,
 * so a caller can size (or ualloc) a model-sized region before any chunk has
 * landed, instead of waiting for the download to size it. */
export const MODEL_BYTES = manifest.model.bytes;

function chunkOffsets(chunks: AssetEntry[]): number[] {
  const offsets: number[] = [];
  let o = 0;
  for (const c of chunks) {
    offsets.push(o);
    o += c.bytes;
  }
  return offsets;
}

/** How the assets arrived, reported once, when they all have. */
export interface LoadStats {
  bytes: number;
  elapsedMs: number;
  /** every asset came out of the Cache API */
  fromCache: boolean;
  /** how many of `bytes` came out of the Cache API (the rest were downloaded) */
  cachedBytes: number;
}

/**
 * Read one contiguous byte range of the model without ever holding the whole
 * artifact, by fetching only the chunk(s) that cover it (Cache-API-hit after
 * the first visit, so usually no network at all).
 *
 * The alternative, `Codec.load({ keepModel: true })`, allocates a second
 * full 124.8 MiB JS copy of the artifact and pins it for the life of the page,
 * to read one ~340 KiB `wpe` slice and nothing else: ~276 MiB steady state on
 * the page most likely to be killed on iOS, against ~151 MiB plus this slice.
 */
export async function fetchModelSlice(offset: number, length: number): Promise<Uint8Array> {
  // Same preflight `loadStreaming` does: without it a non-secure context
  // spends `download`'s two backoff sleeps before surfacing the same named
  // error.
  assertSecureContext();
  const chunks = manifest.model.chunks;
  const offsets = chunkOffsets(chunks);
  const end = offset + length;
  if (offset < 0 || end > manifest.model.bytes) {
    throw new Error(`model slice [${offset}, ${end}) is outside the ${manifest.model.bytes}-byte artifact`);
  }
  const out = new Uint8Array(length);
  for (let i = 0; i < chunks.length; i++) {
    const start = offsets[i];
    const stop = start + chunks[i].bytes;
    if (stop <= offset || start >= end) continue;
    // eslint-disable-next-line no-await-in-loop -- at most two chunks for any slice this reads; sequential keeps peak memory to one chunk
    const bytes = await fetchAsset(chunks[i], () => {});
    const from = Math.max(offset, start) - start;
    const to = Math.min(end, stop) - start;
    out.set(bytes.subarray(from, to), start + from - offset);
  }
  return out;
}

export interface LoadCallbacks {
  /** The (small) wasm binary, verified. Fires first, well before the model
   * chunks are done, so the caller can start compiling/instantiating while
   * the rest of the download is still in flight. */
  onWasm: (bytes: Uint8Array) => void;
  /** One model chunk, verified, with its absolute byte offset into the
   * assembled model. Fires per chunk, in whatever order the 3-way fetch
   * pool finishes them (not necessarily offset order). */
  onChunk: (offset: number, bytes: Uint8Array) => void;
  onTokenizer: (bytes: Uint8Array) => void;
  onProgress: (p: Progress) => void;
}

/**
 * Stream every asset to its callback the moment it's downloaded+verified (or
 * served from cache), with one bytes-weighted progress signal across all of
 * them, 3 fetches at a time. `signal` aborts every in-flight and queued
 * fetch; `client.ts` uses it to stop downloading a model a failed tier is
 * going to throw away. Unlike a fetch-then-assemble pass, no assembled
 * ~125 MiB model buffer is ever held here: callers that need the model
 * chunks contiguous (in wasm memory, or as a kept copy) assemble it
 * themselves as chunks arrive. The wasm entry is placed first in the fetch
 * queue so it's requested (and, being small, usually finishes) well ahead of
 * any model chunk.
 */
export async function loadStreaming(wasmEntry: AssetEntry, cb: LoadCallbacks, signal?: AbortSignal): Promise<LoadStats> {
  // Fail in a second, before ~125 MiB moves, if this page cannot verify a
  // single byte of it (see assertSecureContext).
  assertSecureContext();
  await pruneCache();
  const chunks = manifest.model.chunks;
  const offsets = chunkOffsets(chunks);
  const items: AssetEntry[] = [wasmEntry, ...chunks, manifest.tokenizer];
  const got = new Array(items.length).fill(0);
  const fromCache = new Array<boolean>(items.length).fill(false);
  const total = items.reduce((a, b) => a + b.bytes, 0);
  const t0 = performance.now();
  const meter = new RateMeter();
  let lastTxt = 0;
  const report = () => {
    const g = got.reduce((a, b) => a + b, 0);
    const now = performance.now();
    const f = g / total;
    meter.push(now, got.reduce((acc, b, i) => acc + (fromCache[i] ? 0 : b), 0));
    if (now - lastTxt > 100 || g === total) {
      lastTxt = now;
      // "every byte so far is a cache hit" is the honest test while the load
      // is still running: one uncached asset flips the line to the download
      // form the moment its first byte lands. `downloadParts`'s restore line
      // quotes `got` alongside `total` in that state: while only the ~1 MB
      // wasm has come back it must not claim to be restoring 125.6 MB.
      const cachedBytes = got.reduce((acc, b, i) => acc + (fromCache[i] ? b : 0), 0);
      const parts = downloadParts({
        got: g,
        total,
        elapsedMs: now - t0,
        rate: meter.rate(),
        etaMs: meter.eta(total - g),
        fromCache: g > 0 && cachedBytes === g,
      });
      cb.onProgress({ fraction: f, text: partsText(parts), parts });
    } else {
      cb.onProgress({ fraction: f });
    }
  };
  let next = 0;
  const workers = Array.from({ length: 3 }, async () => {
    for (;;) {
      const i = next++;
      if (i >= items.length) return;
      const bytes = await fetchAsset(
        items[i],
        (b, cacheHit) => {
          got[i] = b;
          if (cacheHit) fromCache[i] = true;
          report();
        },
        signal,
      );
      if (i === 0) cb.onWasm(bytes);
      else if (i <= chunks.length) cb.onChunk(offsets[i - 1], bytes);
      else cb.onTokenizer(bytes);
    }
  });
  await Promise.all(workers);
  return {
    bytes: total,
    elapsedMs: performance.now() - t0,
    fromCache: fromCache.every(Boolean),
    cachedBytes: got.reduce((acc, b, i) => acc + (fromCache[i] ? b : 0), 0),
  };
}
